### ISSUE TITLE
这一堆东西怎么用呢？

### ISSUE THREAD

**Issue by fefz** [yuanxin69/m3u#1]
**一头雾水**

**Comment by trytrytogo** [comment]
很不错的，现在一个一个加，自己再想想怎么搞。

**Comment by longsiew** [comment]
大哥请问你是脱壳拿出来的吗？想学脱壳可以教吗

**Comment by trytrytogo** [comment]
我觉得可能是抓包的。我抓过一些，不完整。

**Comment by yuanxin69** [comment]
Yes

**Comment by longsiew** [comment]
可以教我吗？

2017-02-13 20:37 GMT+08:00 yuanxin69 <notifications@github.com>:

**Comment by longsiew** [comment]
那个龙马TV是我做的

2017-02-14 11:27 GMT+08:00 siew long <hyper88@gmail.com>:

**Comment by longsiew** [comment]
老大收不收徒

2017年2月14日 11:31 AM，"siew long" <hyper88@gmail.com>写道：

**Comment by yuanxin69** [comment]
对不起，无意冒犯你了，有事可以交流。

2017-02-14 13:24 GMT+08:00 longsiew <notifications@github.com>:

**Comment by longsiew** [comment]
没事大家就是学习

2017年2月14日 3:03 PM，"yuanxin69" <notifications@github.com>写道：

**Comment by longsiew** [comment]
请问你是用什么脱壳工具

2017年2月14日 3:05 PM，"siew long" <hyper88@gmail.com>写道：

**Comment by longsiew** [comment]
解固重点是不是在so里

2017年2月14日 3:34 PM，"siew long" <hyper88@gmail.com>写道：

**Comment by longsiew** [comment]
？

2017年2月14日 3:38 PM，"siew long" <hyper88@gmail.com>写道：

**Comment by longsiew** [comment]
老大可以帮我脱这个壳吗？ 这个里面可以放link key
没有key 软件很难玩了😢

2017-02-16 8:58 GMT+08:00 siew long <hyper88@gmail.com>:
